# -*- coding: utf-8 -*-
"""00_HelloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wieQIkFh1Etf4_jYtrdDNb-0kvx3mKEu
"""

# Este símbolo se utiliza para comentar el código.
print("Hola grupo 230 de la carrera técnica de PROGRAMACIÓN")

# Cómo consultar el tipo de dato
print(type("Soy un dato str"))  # Tipo 'str'
print(type(5))  # Tipo 'int'
print(type(1.5))  # Tipo 'float'
print(type(3 + 1j))  # Tipo 'complex'
print(type(True))  # Tipo 'bool'
print(type("Mi cadena de texto"))  # Tipo 'NoneType'